import turtle

t = turtle.Pen()
# t.hideturtle()
from random import randint, random

turtle.Screen().bgcolor('dark blue')
# star_num = 0

# def draw_star(points, size, col, x, y):
#     turtle.penup()
#     turtle.goto(x,y)
#     turtle.pendown()
#     angle = 180 - (180 / points)
#     turtle.color(col)
#     turtle.begin_fill()
#     for i in range(points):
#         turtle.forward(size)
#         turtle.right(angle)
#     turtle.end_fill()
    
# while (star_num < 10):
#     ranPts = randint(2, 5) * 2 + 1
#     ranSize = randint(10, 50)
#     ranX = randint(-350, 300)
#     ranY = randint(-250, 250)
#     ranCol = (random(), random(), random())
#     draw_star(ranPts, ranSize, ranCol, ranX, ranY)
#     star_num = star_num + 1

t.speed(10)
t.color(0,0,1)
t.begin_fill()
t.forward(300)
t.left(90)
t.forward(30)
t.left(90)
t.forward(20)
t.right(90)
t.forward(40)
t.left(90) 
t.forward(100)
t.right(90)
t.forward(100)
t.right(50)

t.color(0,1,1)

t.begin_fill()
t.circle(100)
t.end_fill()
t.color(0,0,1)
t.begin_fill()
t.right(130)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(85)
t.left(180)
t.forward(85)
t.begin_fill()

t.color(0.5,0.5,0.5)
t.left(90)
t.forward(30)
t.left(90)
t.forward(20)
t.right(90)
t.forward(40)
t.right(90)
t.forward(20)
t.end_fill()

t.color(0,0,1)
# t.begin_fill()
t.right(90)
t.forward(150)
t.left(90)
t.forward(70)
# t.end_fill()

t.left(90)
t.begin_fill()
t.forward(300)
t.left(90)
t.forward(30)
t.left(90)
t.forward(20)
t.right(90)
t.forward(40)
t.left(90) 
t.forward(280)
t.left(90)
t.forward(70)
t.end_fill()

t.up()
t.forward(20)
t.down()
t.color(0,0,0)
t.begin_fill()
t.circle(20)
t.end_fill()
t.left(90)
t.up()
t.forward(270)
t.right(90)
t.down()
t.begin_fill()
t.circle(20)
t.end_fill()


turtle.done()